services:
  db_dev:
    image: postgres:18
    container_name: django-db-dev
    env_file:
      - .env.dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - django_db_dev:/var/lib/postgresql
    ports:
      - "5434:5432"

  web_dev:
    build: .
    container_name: django-web-dev
    env_file:
      - .env.dev
    depends_on:
      db_dev:
        condition: service_healthy
    volumes:
      - .:/app
      - django_venv_dev:/app/.venv
    ports:
      - "8004:8000"
    user: "${UID:-1000}:${GID:-1000}"
    command: >
      sh -c '
        until /app/.venv/bin/python manage.py migrate --noinput >/dev/null 2>&1; do
          sleep 1;
        done;
        /app/.venv/bin/python manage.py runserver 0.0.0.0:8000
      '

  db_prod:
    image: postgres:18
    container_name: django-db-prod
    env_file:
      - .env.prod
    volumes:
      - django_db_prod:/var/lib/postgresql
    ports:
      - "5435:5432"

  web_prod:
    build:
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: django-web-prod
    env_file:
      - .env.prod
    depends_on:
      - db_prod
    ports:
      - "8005:8000"
    user: "${UID:-1000}:${GID:-1000}"
    command: sh -c "python manage.py collectstatic --noinput && gunicorn base_django.wsgi:application --bind 0.0.0.0:8000 --workers 3 --log-file -"

volumes:
  django_db_dev:
  django_db_prod:
  django_venv_dev:
