# Generated by Django 6.0.4 on 2026-05-04 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Artículo')),
                ('precio_referencia', models.IntegerField()),
                ('vida_util_referencia_meses', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finanzas_personales.categoria')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finanzas_personales.habitacion')),
            ],
            options={
                'verbose_name_plural': 'Artículos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('precio_compra', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_reemplazo', models.DateField(blank=True, null=True, verbose_name='Fecha de Reemplazo Forzado')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('estado', models.CharField(choices=[('en_uso', 'En Uso'), ('desecho', 'Desecho')], default='en_uso', max_length=20)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finanzas_personales.articulo')),
            ],
            options={
                'verbose_name_plural': 'Compras',
                'ordering': ['articulo', 'fecha_compra'],
            },
        ),
    ]
